package com.capsule.app.understanding

enum class UnderstandingSourceGlyphKind { PROVIDER, APP, GENERIC_CATEGORY, UNKNOWN }

enum class CanonicalUrlRole { PRIMARY, SUPPORTING }

enum class EvidenceKind {
    SAVED_TEXT,
    SAVED_URL,
    URL_METADATA,
    READABLE_PUBLIC_TEXT,
    OCR_TEXT,
    DOCUMENT_METADATA,
    MEDIA_METADATA,
    TRANSCRIPT,
    SCREENSHOT_REFERENCE,
    USER_CORRECTION,
    FETCH_LIMITATION,
    MODEL_LIMITATION
}

enum class EvidenceStatus { READY, PARTIAL, LIMITED, FAILED, SUPPRESSED, INVALIDATED }

enum class EvidenceRetentionClass {
    LOCAL_RAW_ALLOWED,
    LOCAL_REFERENCE_ONLY,
    CONTENT_FREE_TRACE,
    EPHEMERAL,
    DELETED_INVALIDATED
}

enum class AcquisitionDepth { BASIC, SMART, DEEP, MANUAL_OVERRIDE }

enum class AcquisitionMethod {
    LOCAL_CAPTURE,
    LOCAL_PARSE,
    NET_PUBLIC_FETCH,
    PROVIDER_METADATA,
    OCR_LOCAL,
    CLOUD_ENRICHMENT,
    USER_FEEDBACK,
    SUPPRESSED_BY_POLICY,
    FAILED_ATTEMPT
}

enum class UnderstandingDepth { BASIC, SMART, DEEP }

enum class UnderstandingPolicyScope { CAPTURE_OVERRIDE, DOMAIN_SUPPRESSION }

enum class UnderstandingOverrideKind {
    GET_MORE_CONTEXT,
    SUMMARIZE_ONLY_SAVED,
    REFRESH_SOURCE_EVIDENCE,
    SCREENSHOT_ONLY,
    SUPPRESS_DOMAIN_FETCH,
    RESET_TO_GLOBAL
}

enum class UnderstandingJobStatus { PENDING, RUNNING, READY, LIMITED, FAILED, CANCELED, INVALIDATED }

enum class CaptureUnderstandingStatus { READY, PARTIAL, LIMITED, FAILED, INVALIDATED }

enum class RetryEligibility { RETRYABLE, NOT_RETRYABLE, USER_ACTION_REQUIRED }

enum class LimitationCode {
    METADATA_ONLY,
    VISUAL_ONLY,
    LOW_CONFIDENCE,
    BLOCKED_SOURCE,
    PRIVATE_SOURCE,
    PAYWALLED_SOURCE,
    FAILED_FETCH,
    CLOUD_DISABLED,
    NETWORK_UNAVAILABLE,
    BUDGET_BLOCKED,
    SENSITIVE_SOURCE,
    DOMAIN_SUPPRESSED,
    BROWSER_FALLBACK_NOT_AVAILABLE,
    SUMMARIZE_ONLY_SAVED
}

enum class CorrectionFeedbackKind {
    WRONG_SOURCE,
    WRONG_SUMMARY,
    NOT_RELEVANT,
    TOO_MUCH_CONTEXT,
    SUPPRESS_DOMAIN,
    SUPPRESS_SOURCE,
    OTHER
}

enum class InvalidationReason {
    CAPTURE_DELETED,
    USER_INVALIDATED,
    CORRECTION_SUPERSEDED,
    SOURCE_STALE,
    DOMAIN_SUPPRESSED,
    CLOUD_RECEIPT_PENDING,
    CLOUD_RECEIPT_CONFIRMED
}

enum class DownstreamEligibility { INELIGIBLE, PARTIALLY_ELIGIBLE, RE_EVALUATION_REQUIRED }

enum class CloudReceiptStatus { NOT_APPLICABLE, PENDING, CONFIRMED, FAILED }

enum class TraceOutcome { SUCCESS, PARTIAL, LIMITED, FAILED, SUPPRESSED, INVALIDATED }